controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\KittenCourse;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

  /**
   * Defines the URL route for the React page.
   *
   * @return array
   */
  public function actionReactPageRoute()
  {
    return ['site/react-page'];
  }

  /**
   * Used to display pages with react
   *
   * @return string
   */
  public function actionMyKittensList()
  {
    $this->layout = 'react_layout';
    return $this->render('kittens_list');
  }

}

views/layouts/_header.php
<?php

use yii\helpers\Html;
use yii\bootstrap5\NavBar;
use yii\bootstrap5\Nav;

NavBar::begin([
  'brandLabel' => Html::img('@web/logo.png', ['alt'=>Yii::$app->name]),
  'brandUrl' => Yii::$app->homeUrl,
  'options' => [
    'class' => 'navbar-expand-md fixed-top navbar-light bg-light',
  ],
]);
echo Nav::widget([
  'options' => ['class' => 'navbar-nav mr-auto'],
  'items' => [
    ['label' => 'Item 1', 'url' => ['/site/my-kittens-list']],
    ['label' => 'Item 2', 'url' => ['/site/my-kittens-list']],
    ['label' => 'Item 3', 'url' => ['/site/my-kittens-list']],
    ['label' => 'Item 4', 'url' => ['/site/my-kittens-list']],
    ['label' => 'Item 5', 'url' => ['/site/my-kittens-list']],
  ],
]);
echo '<div class="nav-item dropdown">';
echo Html::a('Language', '#', ['class' => 'nav-link dropdown-toggle', 'data-toggle' => 'dropdown']);
print_r(
  '<div class="dropdown-menu">
                <a class="dropdown-item" href="#">УКР</a>
                <a class="dropdown-item" href="#">ENG</a>
             </div>
          </div>
        <button class="btn btn-primary ml-2">Button 1</button>
        <button class="btn btn-secondary ml-2">Button 2</button>
        <a href="/site/my-kittens-list">
        <img src="avatar.jpg" class="ml-2 rounded-circle" width="32" height="32" alt="Avatar">
        </a>'
);

NavBar::end();
?>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;

AppAsset::register($this);

$this->registerCsrfMetaTags();
$this->registerMetaTag(['charset' => Yii::$app->charset], 'charset');
$this->registerMetaTag(['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no']);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['meta_description'] ?? '']);
$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['meta_keywords'] ?? '']);
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => Yii::getAlias('@web/favicon.ico')]);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header id="header">
    <!-- Include header partial -->
    <?= $this->render('/layouts/_header') ?>
</header>

<main id="main" class="flex-shrink-0" role="main">
    <div class="container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer id="footer" class="mt-auto py-3 bg-light">
    <div class="container">
        <div class="row text-muted">
            <div class="col-md-6 text-center text-md-start">&copy; My Company <?= date('Y') ?></div>
            <div class="col-md-6 text-center text-md-end"><?= Yii::powered() ?></div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/react_layout.php
<?php
use yii\helpers\Html;
use app\assets\AppAsset;
use app\widgets\Alert;

// Register the AppAsset
AppAsset::register($this);

// Begin the page
$this->beginPage();
?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>

	<!-- Load React dependencies -->
	<script src="https://unpkg.com/react@18.2.0/umd/react.development.js"></script>
	<script src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.development.js"></script>

	<!-- Include the bundle.js file -->
	<script src="<?= Yii::$app->request->baseUrl ?>/react-front/dist/bundle.js"></script>
	<?php echo \yii\helpers\Html::csrfMetaTags(); ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header id="header">
	<!-- Include header partial -->
	<?= $this->render('/layouts/_header') ?>
</header>

<main id="react-main" class="flex-shrink-0" role="main">
	<div class="react-container">
		<?= Alert::widget() ?>

		<!-- React container -->
		<div id="profile-container"></div>
	</div>
</main>

<footer id="footer" class="mt-auto py-3 bg-light">
	<div class="container">
		<div class="row text-muted">
			<div class="col-md-6 text-center text-md-start">&copy; My Company <?= date('Y') ?></div>
			<div class="col-md-6 text-center text-md-end"><?= Yii::powered() ?></div>
		</div>
	</div>
</footer>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>